# Generated by Django 5.1.7 on 2025-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název služby')),
                ('main_image', models.ImageField(upload_to='services/main/', verbose_name='Hlavní obrázek')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Vedlejší obrázek')),
                ('short_description', models.TextField(max_length=300, verbose_name='Krátký popis')),
                ('description', models.TextField(verbose_name='Detailní popis')),
            ],
        ),
    ]
